# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
# trigger:
#   branches:
#     include:
#       - main

pool:
  vmImage: ubuntu-latest

steps: 
  - script: |
      #git remote add nve_github https://github.com/NVE/fram-core.git
      git branch
      #git fetch github
      #git push github main
    displayName: 'Sync changes to GitHub'
    env:
      GITHUB_PAT: $(GITHUB_PAT)

# variables:
#   PYTHON_VERSION: '3.12'
#   ARTIFACT_FEED: 'Modellrammeverk_NG/NVE.Modellrammeverk_NG'

# stages:
#   - stage: BuildPackageStage
#     jobs:
#       - job: BuildPackageJob
#         displayName: 'Build package'

#         steps:
#           - task: UsePythonVersion@0
#             displayName: 'Use Python $(PYTHON_VERSION)'
#             inputs:
#               versionSpec: '$(PYTHON_VERSION)'
#               addToPath: true

#           - script: |
#               python -m build
#             displayName: 'Build package'

#           # - script: |
#           #     poetry config repositories.azure-feed https://pkgs.dev.azure.com/NVE-devops/Modellrammeverk_NG/_packaging/NVE.Modellrammeverk_NG/pypi/upload/
#           #     poetry config http-basic.azure-feed $(ARTIFACT_FEED_USERNAME) $(ARTIFACT_FEED_PASSWORD)
#           #     poetry publish --repository azure-feed
#           #   displayName: 'Publish package to Azure DevOps Artifacts'